[package]
name = "libxl"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
widestring = "1.0.2"
num="0.4.1"


[build-dependencies]
bindgen = "0.69.1"